Docker compose
park

first version to test

bugfixing

update install

fix dir

install

update

almost working

bugfix

move to trace level for now

log file name

logging

bugfix

pep8

next

wip

adding hunter

telehack

update

work in progress

now to test

we need to make sure the app is called correctly.

   main:create_app

in swarms/api/systemd/uvicorn.service

force pull

fixup

logging

wip

wip

wip

wip

wip

wip

wip

wip

wip

wip

wip

wip

adding scripts

bugfix

wip

wip

wip

wip

wip

no more sock

update

wip

wip

bugfix install useradd

switch branch

get rid of local

ignore error on user

more local

more local

bugfix APT

rerun

adding nginx

adding expect for unbuffer debugging

start nginx

bugfix print

hf_home and aws-cli

bugfix

adding values for undefined variables
+        key_name = "fixme"
+        user_id = "fixme"

merge fix

now for the free tier ubuntu

wip

example

cleanup

remove emacs

update

terminate spot instances as well

bugfix

https://meta-introspector.sentry.io/issues/14387352/?query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&stream_index=0

multiprocessing/process.py
in
_bootstrap
at line
329

ModuleNotFoundError
No module named 'pathos'

removing callbacks

for flexibility and security we dont want to have hard coded callbacks
in the code

now lets add a sleep to wait for swarms

removing prints

OSError: [Errno 5] Input/output error
  File "src/hunter/_tracer.pyx", line 45, in hunter._tracer.trace_func
  File "src/hunter/_predicates.pyx", line 587, in hunter._predicates.fast_call
  File "src/hunter/_predicates.pyx", line 360, in hunter._predicates.fast_When_call
  File "main.py", line 56, in process_hunter_event
    print("MOD", mod)

OSError: [Errno 5] Input/output error
(3 additional frame(s) were not displayed

starting the documentation of terraform

check api status

now testing

test working

adding pip freeze

fix bug

rebase

just run

just run

bootfast

update just run

start of cloudwatch logs

now remove the branch

remove checkout

just run

dont echo

remove echo

adding in the new install for systemd and nginx from swarms.

we will move this out into ssm files we can apply on boot later

update

update

wip

build dockerfile in github

building

Update docker-image.yml

wip readme

start of dockerization

create boot script to be called from ssm

adding header

adding docker boot

going to test

shell check

update

rundocker bugfix

expose on network

docker

adding torch and together

compose tests

compose test